from .personal import PERSONAL_FIELDS
from .vehicle import VEHICLE_FIELDS
from .finance import FINANCE_FIELDS
from .education import EDUCATION_FIELDS
from .medical import MEDICAL_FIELDS
from .government import GOVERNMENT_FIELDS

FIELD_ALIASES = {}

FIELD_ALIASES.update(PERSONAL_FIELDS)
FIELD_ALIASES.update(VEHICLE_FIELDS)
FIELD_ALIASES.update(FINANCE_FIELDS)
FIELD_ALIASES.update(EDUCATION_FIELDS)
FIELD_ALIASES.update(MEDICAL_FIELDS)
FIELD_ALIASES.update(GOVERNMENT_FIELDS)